import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const tickets = [
  {
    title: "Ticket 1",
    content: "Content for ticket 1 from database",
    status: "DONE" as const,
    bounty: 100,
    deadline: new Date().toISOString().split("T")[0],
  },
  {
    title: "Ticket 2",
    content: "Content for ticket 2 from database",
    status: "OPEN" as const,
    bounty: 50,
    deadline: new Date().toISOString().split("T")[0],
  },
  {
    title: "Ticket 3",
    content: "Content for ticket 3 from database",
    status: "IN_PROGRESS" as const,
    bounty: 25,
    deadline: new Date().toISOString().split("T")[0],
  },
];

const seed = async () => {
  // Note: this is a safeguard to ensure that the database is empty before seeding

  // Note: The .ticket property is automatically generated by Prisma based on the schema.prisma file in your project. Prisma creates a lowercase (camelCase) property on the client instance so you can interact with that specific database table. Because the model is named Ticket (capital T), the Prisma Client exposes prisma.ticket (lowercase t). This property contains all the built-in database methods (deleteMany, createMany, findUnique, etc.) specifically mapped to that table.
  await prisma.ticket.deleteMany();
  // Note: two ways to seed data
  /*  for (const ticket of tickets) {
    await prisma.ticket.create({
      data: ticket,
    });
  } */
  /* 
    const promises = tickets.map(async (ticket) => {
      await prisma.ticket.create({
        data: ticket,
      });

      await Promise.all(promises);
    ; */

  await prisma.ticket.createMany({
    data: tickets,
  });
};

seed();
